### ISSUE TITLE
Build Does Not Work

### ISSUE THREAD

**Issue by gudenau** [nicholaschum/masquerade#13]
When attempting to build an Oreo ROM with interfacer the build fails with a few Java errors. 

- `FORCE_AUTHORIZE_SUBSTRATUM_PACKAGES` does not exist.
- `deletePackageAsUser` is missing a parameter.
- `setEnabled` is missing a parameter.
- `recreateDefaults` does not exist.

```
ERROR: packages/services/ThemeInterfacer/app/src/main/java/projekt/interfacer/services/JobService.java:140.41: FORCE_AUTHORIZE_SUBSTRATUM_PACKAGES cannot be resolved or is not a field
ERROR: packages/services/ThemeInterfacer/app/src/main/java/projekt/interfacer/services/JobService.java:477.41: FORCE_AUTHORIZE_SUBSTRATUM_PACKAGES cannot be resolved or is not a field
ERROR: packages/services/ThemeInterfacer/app/src/main/java/projekt/interfacer/services/JobService.java:481.33: FORCE_AUTHORIZE_SUBSTRATUM_PACKAGES cannot be resolved or is not a field
ERROR: packages/services/ThemeInterfacer/app/src/main/java/projekt/interfacer/services/JobService.java:525.21: The method deletePackageAsUser(String, int, IPackageDeleteObserver, int, int) in the type IPackageManager is not applicable for the arguments (String, IPackageDeleteObserver, int, int)
ERROR: packages/services/ThemeInterfacer/app/src/main/java/projekt/interfacer/services/JobService.java:536.22: The method setEnabled(String, boolean, int) in the type IOverlayManager is not applicable for the arguments (String, boolean, int, boolean)
ERROR: services/ThemeInterfacer/app/src/main/java/projekt/interfacer/services/JobService.java:644.18: The method recreateDefaults() is undefined for the type Typeface
```

**Comment by msfjarvis** [comment]
You're building interfacer in Android 8.1.0, where it's deprecated and superseded by
[SubstratumService](https://substratum.review/#/q/topic:sysserv). Please use that in place of interfacer.

**Comment by gudenau** [comment]
I'm sorry, but how do I set up the manifest to download this? The website does not appear to show anything that would allow me to do that, first time I have seen it.

**Comment by msfjarvis** [comment]
@gudenau you don't have to track any repository from us anymore, simply merge our changes into your repositories.

**Comment by gudenau** [comment]
How do I view said changes?

**Comment by msfjarvis** [comment]
I linked them in my very first comment on this issue.

**Comment by gudenau** [comment]
I'm sorry, I don't understand how to do that with that interface.
